version: "3.7"

services:

  php-fpm:
    build:
      dockerfile: ./.docker/php-fpm/Dockerfile
      context: ./
    container_name: ${docker_project}-php-fpm
    environment:
      XDEBUG_CONFIG: "remote_host=${docker_php_xdebug_remote_host}"
#      PHP_IDE_CONFIG: "serverName=${docker_php_ide_server_name}"
    volumes:
      - ./:/opt/app
    networks:
      php-network:

  nginx:
    build:
      dockerfile: ./.docker/nginx/Dockerfile
      context: ./
    container_name: ${docker_project}-nginx
    ports:
      - "80:80"
    volumes:
      - ./:/opt/app
      - ./.docker/nginx/conf.d/default.cakephp3.conf:/etc/nginx/conf.d/default.conf
    networks:
      php-network:

networks:
  php-network:
    name: dev-php-network
    driver: bridge
